// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobbyMessages.proto

package proto_files;

public final class LobbyMessages {
  private LobbyMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LiteRoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_files.LiteRoom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 room_id = 1;</code>
     * @return The roomId.
     */
    int getRoomId();

    /**
     * <code>string room_name = 2;</code>
     * @return The roomName.
     */
    java.lang.String getRoomName();
    /**
     * <code>string room_name = 2;</code>
     * @return The bytes for roomName.
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();

    /**
     * <code>int32 count_users = 3;</code>
     * @return The countUsers.
     */
    int getCountUsers();
  }
  /**
   * Protobuf type {@code proto_files.LiteRoom}
   */
  public static final class LiteRoom extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_files.LiteRoom)
      LiteRoomOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LiteRoom.newBuilder() to construct.
    private LiteRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LiteRoom() {
      roomName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LiteRoom();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LiteRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              roomId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              roomName_ = s;
              break;
            }
            case 24: {

              countUsers_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_files.LobbyMessages.internal_static_proto_files_LiteRoom_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_files.LobbyMessages.internal_static_proto_files_LiteRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_files.LobbyMessages.LiteRoom.class, proto_files.LobbyMessages.LiteRoom.Builder.class);
    }

    public static final int ROOM_ID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <code>int32 room_id = 1;</code>
     * @return The roomId.
     */
    @java.lang.Override
    public int getRoomId() {
      return roomId_;
    }

    public static final int ROOM_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomName_;
    /**
     * <code>string room_name = 2;</code>
     * @return The roomName.
     */
    @java.lang.Override
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      }
    }
    /**
     * <code>string room_name = 2;</code>
     * @return The bytes for roomName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNT_USERS_FIELD_NUMBER = 3;
    private int countUsers_;
    /**
     * <code>int32 count_users = 3;</code>
     * @return The countUsers.
     */
    @java.lang.Override
    public int getCountUsers() {
      return countUsers_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roomId_ != 0) {
        output.writeInt32(1, roomId_);
      }
      if (!getRoomNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomName_);
      }
      if (countUsers_ != 0) {
        output.writeInt32(3, countUsers_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      if (!getRoomNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomName_);
      }
      if (countUsers_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, countUsers_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_files.LobbyMessages.LiteRoom)) {
        return super.equals(obj);
      }
      proto_files.LobbyMessages.LiteRoom other = (proto_files.LobbyMessages.LiteRoom) obj;

      if (getRoomId()
          != other.getRoomId()) return false;
      if (!getRoomName()
          .equals(other.getRoomName())) return false;
      if (getCountUsers()
          != other.getCountUsers()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      hash = (37 * hash) + ROOM_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRoomName().hashCode();
      hash = (37 * hash) + COUNT_USERS_FIELD_NUMBER;
      hash = (53 * hash) + getCountUsers();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_files.LobbyMessages.LiteRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.LiteRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.LiteRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_files.LobbyMessages.LiteRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_files.LiteRoom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_files.LiteRoom)
        proto_files.LobbyMessages.LiteRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_files.LobbyMessages.internal_static_proto_files_LiteRoom_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_files.LobbyMessages.internal_static_proto_files_LiteRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_files.LobbyMessages.LiteRoom.class, proto_files.LobbyMessages.LiteRoom.Builder.class);
      }

      // Construct using proto_files.LobbyMessages.LiteRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomId_ = 0;

        roomName_ = "";

        countUsers_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_files.LobbyMessages.internal_static_proto_files_LiteRoom_descriptor;
      }

      @java.lang.Override
      public proto_files.LobbyMessages.LiteRoom getDefaultInstanceForType() {
        return proto_files.LobbyMessages.LiteRoom.getDefaultInstance();
      }

      @java.lang.Override
      public proto_files.LobbyMessages.LiteRoom build() {
        proto_files.LobbyMessages.LiteRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto_files.LobbyMessages.LiteRoom buildPartial() {
        proto_files.LobbyMessages.LiteRoom result = new proto_files.LobbyMessages.LiteRoom(this);
        result.roomId_ = roomId_;
        result.roomName_ = roomName_;
        result.countUsers_ = countUsers_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_files.LobbyMessages.LiteRoom) {
          return mergeFrom((proto_files.LobbyMessages.LiteRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_files.LobbyMessages.LiteRoom other) {
        if (other == proto_files.LobbyMessages.LiteRoom.getDefaultInstance()) return this;
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (!other.getRoomName().isEmpty()) {
          roomName_ = other.roomName_;
          onChanged();
        }
        if (other.getCountUsers() != 0) {
          setCountUsers(other.getCountUsers());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_files.LobbyMessages.LiteRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_files.LobbyMessages.LiteRoom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int roomId_ ;
      /**
       * <code>int32 room_id = 1;</code>
       * @return The roomId.
       */
      @java.lang.Override
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>int32 room_id = 1;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 room_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object roomName_ = "";
      /**
       * <code>string room_name = 2;</code>
       * @return The roomName.
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string room_name = 2;</code>
       * @return The bytes for roomName.
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string room_name = 2;</code>
       * @param value The roomName to set.
       * @return This builder for chaining.
       */
      public Builder setRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string room_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomName() {
        
        roomName_ = getDefaultInstance().getRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>string room_name = 2;</code>
       * @param value The bytes for roomName to set.
       * @return This builder for chaining.
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomName_ = value;
        onChanged();
        return this;
      }

      private int countUsers_ ;
      /**
       * <code>int32 count_users = 3;</code>
       * @return The countUsers.
       */
      @java.lang.Override
      public int getCountUsers() {
        return countUsers_;
      }
      /**
       * <code>int32 count_users = 3;</code>
       * @param value The countUsers to set.
       * @return This builder for chaining.
       */
      public Builder setCountUsers(int value) {
        
        countUsers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count_users = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountUsers() {
        
        countUsers_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_files.LiteRoom)
    }

    // @@protoc_insertion_point(class_scope:proto_files.LiteRoom)
    private static final proto_files.LobbyMessages.LiteRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_files.LobbyMessages.LiteRoom();
    }

    public static proto_files.LobbyMessages.LiteRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LiteRoom>
        PARSER = new com.google.protobuf.AbstractParser<LiteRoom>() {
      @java.lang.Override
      public LiteRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LiteRoom(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LiteRoom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LiteRoom> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto_files.LobbyMessages.LiteRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateRoomsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_files.UpdateRoomsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code proto_files.UpdateRoomsRequest}
   */
  public static final class UpdateRoomsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_files.UpdateRoomsRequest)
      UpdateRoomsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateRoomsRequest.newBuilder() to construct.
    private UpdateRoomsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateRoomsRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateRoomsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateRoomsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_files.LobbyMessages.UpdateRoomsRequest.class, proto_files.LobbyMessages.UpdateRoomsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_files.LobbyMessages.UpdateRoomsRequest)) {
        return super.equals(obj);
      }
      proto_files.LobbyMessages.UpdateRoomsRequest other = (proto_files.LobbyMessages.UpdateRoomsRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.UpdateRoomsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_files.LobbyMessages.UpdateRoomsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_files.UpdateRoomsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_files.UpdateRoomsRequest)
        proto_files.LobbyMessages.UpdateRoomsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_files.LobbyMessages.UpdateRoomsRequest.class, proto_files.LobbyMessages.UpdateRoomsRequest.Builder.class);
      }

      // Construct using proto_files.LobbyMessages.UpdateRoomsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsRequest_descriptor;
      }

      @java.lang.Override
      public proto_files.LobbyMessages.UpdateRoomsRequest getDefaultInstanceForType() {
        return proto_files.LobbyMessages.UpdateRoomsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public proto_files.LobbyMessages.UpdateRoomsRequest build() {
        proto_files.LobbyMessages.UpdateRoomsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto_files.LobbyMessages.UpdateRoomsRequest buildPartial() {
        proto_files.LobbyMessages.UpdateRoomsRequest result = new proto_files.LobbyMessages.UpdateRoomsRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_files.LobbyMessages.UpdateRoomsRequest) {
          return mergeFrom((proto_files.LobbyMessages.UpdateRoomsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_files.LobbyMessages.UpdateRoomsRequest other) {
        if (other == proto_files.LobbyMessages.UpdateRoomsRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_files.LobbyMessages.UpdateRoomsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_files.LobbyMessages.UpdateRoomsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_files.UpdateRoomsRequest)
    }

    // @@protoc_insertion_point(class_scope:proto_files.UpdateRoomsRequest)
    private static final proto_files.LobbyMessages.UpdateRoomsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_files.LobbyMessages.UpdateRoomsRequest();
    }

    public static proto_files.LobbyMessages.UpdateRoomsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateRoomsRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateRoomsRequest>() {
      @java.lang.Override
      public UpdateRoomsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateRoomsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateRoomsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateRoomsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto_files.LobbyMessages.UpdateRoomsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateRoomsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_files.UpdateRoomsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    java.util.List<proto_files.LobbyMessages.LiteRoom> 
        getLiteRoomList();
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    proto_files.LobbyMessages.LiteRoom getLiteRoom(int index);
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    int getLiteRoomCount();
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    java.util.List<? extends proto_files.LobbyMessages.LiteRoomOrBuilder> 
        getLiteRoomOrBuilderList();
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    proto_files.LobbyMessages.LiteRoomOrBuilder getLiteRoomOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto_files.UpdateRoomsResponse}
   */
  public static final class UpdateRoomsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_files.UpdateRoomsResponse)
      UpdateRoomsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateRoomsResponse.newBuilder() to construct.
    private UpdateRoomsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateRoomsResponse() {
      liteRoom_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateRoomsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateRoomsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                liteRoom_ = new java.util.ArrayList<proto_files.LobbyMessages.LiteRoom>();
                mutable_bitField0_ |= 0x00000001;
              }
              liteRoom_.add(
                  input.readMessage(proto_files.LobbyMessages.LiteRoom.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          liteRoom_ = java.util.Collections.unmodifiableList(liteRoom_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_files.LobbyMessages.UpdateRoomsResponse.class, proto_files.LobbyMessages.UpdateRoomsResponse.Builder.class);
    }

    public static final int LITEROOM_FIELD_NUMBER = 1;
    private java.util.List<proto_files.LobbyMessages.LiteRoom> liteRoom_;
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    @java.lang.Override
    public java.util.List<proto_files.LobbyMessages.LiteRoom> getLiteRoomList() {
      return liteRoom_;
    }
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends proto_files.LobbyMessages.LiteRoomOrBuilder> 
        getLiteRoomOrBuilderList() {
      return liteRoom_;
    }
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    @java.lang.Override
    public int getLiteRoomCount() {
      return liteRoom_.size();
    }
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    @java.lang.Override
    public proto_files.LobbyMessages.LiteRoom getLiteRoom(int index) {
      return liteRoom_.get(index);
    }
    /**
     * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
     */
    @java.lang.Override
    public proto_files.LobbyMessages.LiteRoomOrBuilder getLiteRoomOrBuilder(
        int index) {
      return liteRoom_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < liteRoom_.size(); i++) {
        output.writeMessage(1, liteRoom_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < liteRoom_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, liteRoom_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_files.LobbyMessages.UpdateRoomsResponse)) {
        return super.equals(obj);
      }
      proto_files.LobbyMessages.UpdateRoomsResponse other = (proto_files.LobbyMessages.UpdateRoomsResponse) obj;

      if (!getLiteRoomList()
          .equals(other.getLiteRoomList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLiteRoomCount() > 0) {
        hash = (37 * hash) + LITEROOM_FIELD_NUMBER;
        hash = (53 * hash) + getLiteRoomList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_files.LobbyMessages.UpdateRoomsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_files.LobbyMessages.UpdateRoomsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_files.UpdateRoomsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_files.UpdateRoomsResponse)
        proto_files.LobbyMessages.UpdateRoomsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_files.LobbyMessages.UpdateRoomsResponse.class, proto_files.LobbyMessages.UpdateRoomsResponse.Builder.class);
      }

      // Construct using proto_files.LobbyMessages.UpdateRoomsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLiteRoomFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (liteRoomBuilder_ == null) {
          liteRoom_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          liteRoomBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_files.LobbyMessages.internal_static_proto_files_UpdateRoomsResponse_descriptor;
      }

      @java.lang.Override
      public proto_files.LobbyMessages.UpdateRoomsResponse getDefaultInstanceForType() {
        return proto_files.LobbyMessages.UpdateRoomsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public proto_files.LobbyMessages.UpdateRoomsResponse build() {
        proto_files.LobbyMessages.UpdateRoomsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto_files.LobbyMessages.UpdateRoomsResponse buildPartial() {
        proto_files.LobbyMessages.UpdateRoomsResponse result = new proto_files.LobbyMessages.UpdateRoomsResponse(this);
        int from_bitField0_ = bitField0_;
        if (liteRoomBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            liteRoom_ = java.util.Collections.unmodifiableList(liteRoom_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.liteRoom_ = liteRoom_;
        } else {
          result.liteRoom_ = liteRoomBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_files.LobbyMessages.UpdateRoomsResponse) {
          return mergeFrom((proto_files.LobbyMessages.UpdateRoomsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_files.LobbyMessages.UpdateRoomsResponse other) {
        if (other == proto_files.LobbyMessages.UpdateRoomsResponse.getDefaultInstance()) return this;
        if (liteRoomBuilder_ == null) {
          if (!other.liteRoom_.isEmpty()) {
            if (liteRoom_.isEmpty()) {
              liteRoom_ = other.liteRoom_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLiteRoomIsMutable();
              liteRoom_.addAll(other.liteRoom_);
            }
            onChanged();
          }
        } else {
          if (!other.liteRoom_.isEmpty()) {
            if (liteRoomBuilder_.isEmpty()) {
              liteRoomBuilder_.dispose();
              liteRoomBuilder_ = null;
              liteRoom_ = other.liteRoom_;
              bitField0_ = (bitField0_ & ~0x00000001);
              liteRoomBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLiteRoomFieldBuilder() : null;
            } else {
              liteRoomBuilder_.addAllMessages(other.liteRoom_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_files.LobbyMessages.UpdateRoomsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_files.LobbyMessages.UpdateRoomsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto_files.LobbyMessages.LiteRoom> liteRoom_ =
        java.util.Collections.emptyList();
      private void ensureLiteRoomIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          liteRoom_ = new java.util.ArrayList<proto_files.LobbyMessages.LiteRoom>(liteRoom_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto_files.LobbyMessages.LiteRoom, proto_files.LobbyMessages.LiteRoom.Builder, proto_files.LobbyMessages.LiteRoomOrBuilder> liteRoomBuilder_;

      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public java.util.List<proto_files.LobbyMessages.LiteRoom> getLiteRoomList() {
        if (liteRoomBuilder_ == null) {
          return java.util.Collections.unmodifiableList(liteRoom_);
        } else {
          return liteRoomBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public int getLiteRoomCount() {
        if (liteRoomBuilder_ == null) {
          return liteRoom_.size();
        } else {
          return liteRoomBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public proto_files.LobbyMessages.LiteRoom getLiteRoom(int index) {
        if (liteRoomBuilder_ == null) {
          return liteRoom_.get(index);
        } else {
          return liteRoomBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder setLiteRoom(
          int index, proto_files.LobbyMessages.LiteRoom value) {
        if (liteRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLiteRoomIsMutable();
          liteRoom_.set(index, value);
          onChanged();
        } else {
          liteRoomBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder setLiteRoom(
          int index, proto_files.LobbyMessages.LiteRoom.Builder builderForValue) {
        if (liteRoomBuilder_ == null) {
          ensureLiteRoomIsMutable();
          liteRoom_.set(index, builderForValue.build());
          onChanged();
        } else {
          liteRoomBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder addLiteRoom(proto_files.LobbyMessages.LiteRoom value) {
        if (liteRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLiteRoomIsMutable();
          liteRoom_.add(value);
          onChanged();
        } else {
          liteRoomBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder addLiteRoom(
          int index, proto_files.LobbyMessages.LiteRoom value) {
        if (liteRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLiteRoomIsMutable();
          liteRoom_.add(index, value);
          onChanged();
        } else {
          liteRoomBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder addLiteRoom(
          proto_files.LobbyMessages.LiteRoom.Builder builderForValue) {
        if (liteRoomBuilder_ == null) {
          ensureLiteRoomIsMutable();
          liteRoom_.add(builderForValue.build());
          onChanged();
        } else {
          liteRoomBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder addLiteRoom(
          int index, proto_files.LobbyMessages.LiteRoom.Builder builderForValue) {
        if (liteRoomBuilder_ == null) {
          ensureLiteRoomIsMutable();
          liteRoom_.add(index, builderForValue.build());
          onChanged();
        } else {
          liteRoomBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder addAllLiteRoom(
          java.lang.Iterable<? extends proto_files.LobbyMessages.LiteRoom> values) {
        if (liteRoomBuilder_ == null) {
          ensureLiteRoomIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, liteRoom_);
          onChanged();
        } else {
          liteRoomBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder clearLiteRoom() {
        if (liteRoomBuilder_ == null) {
          liteRoom_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          liteRoomBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public Builder removeLiteRoom(int index) {
        if (liteRoomBuilder_ == null) {
          ensureLiteRoomIsMutable();
          liteRoom_.remove(index);
          onChanged();
        } else {
          liteRoomBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public proto_files.LobbyMessages.LiteRoom.Builder getLiteRoomBuilder(
          int index) {
        return getLiteRoomFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public proto_files.LobbyMessages.LiteRoomOrBuilder getLiteRoomOrBuilder(
          int index) {
        if (liteRoomBuilder_ == null) {
          return liteRoom_.get(index);  } else {
          return liteRoomBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public java.util.List<? extends proto_files.LobbyMessages.LiteRoomOrBuilder> 
           getLiteRoomOrBuilderList() {
        if (liteRoomBuilder_ != null) {
          return liteRoomBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(liteRoom_);
        }
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public proto_files.LobbyMessages.LiteRoom.Builder addLiteRoomBuilder() {
        return getLiteRoomFieldBuilder().addBuilder(
            proto_files.LobbyMessages.LiteRoom.getDefaultInstance());
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public proto_files.LobbyMessages.LiteRoom.Builder addLiteRoomBuilder(
          int index) {
        return getLiteRoomFieldBuilder().addBuilder(
            index, proto_files.LobbyMessages.LiteRoom.getDefaultInstance());
      }
      /**
       * <code>repeated .proto_files.LiteRoom liteRoom = 1;</code>
       */
      public java.util.List<proto_files.LobbyMessages.LiteRoom.Builder> 
           getLiteRoomBuilderList() {
        return getLiteRoomFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto_files.LobbyMessages.LiteRoom, proto_files.LobbyMessages.LiteRoom.Builder, proto_files.LobbyMessages.LiteRoomOrBuilder> 
          getLiteRoomFieldBuilder() {
        if (liteRoomBuilder_ == null) {
          liteRoomBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto_files.LobbyMessages.LiteRoom, proto_files.LobbyMessages.LiteRoom.Builder, proto_files.LobbyMessages.LiteRoomOrBuilder>(
                  liteRoom_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          liteRoom_ = null;
        }
        return liteRoomBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_files.UpdateRoomsResponse)
    }

    // @@protoc_insertion_point(class_scope:proto_files.UpdateRoomsResponse)
    private static final proto_files.LobbyMessages.UpdateRoomsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_files.LobbyMessages.UpdateRoomsResponse();
    }

    public static proto_files.LobbyMessages.UpdateRoomsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateRoomsResponse>
        PARSER = new com.google.protobuf.AbstractParser<UpdateRoomsResponse>() {
      @java.lang.Override
      public UpdateRoomsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateRoomsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateRoomsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateRoomsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto_files.LobbyMessages.UpdateRoomsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_files_LiteRoom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_files_LiteRoom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_files_UpdateRoomsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_files_UpdateRoomsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_files_UpdateRoomsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_files_UpdateRoomsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023LobbyMessages.proto\022\013proto_files\"C\n\010Li" +
      "teRoom\022\017\n\007room_id\030\001 \001(\005\022\021\n\troom_name\030\002 \001" +
      "(\t\022\023\n\013count_users\030\003 \001(\005\"\024\n\022UpdateRoomsRe" +
      "quest\">\n\023UpdateRoomsResponse\022\'\n\010liteRoom" +
      "\030\001 \003(\0132\025.proto_files.LiteRoomB\017B\rLobbyMe" +
      "ssagesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_files_LiteRoom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_files_LiteRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_files_LiteRoom_descriptor,
        new java.lang.String[] { "RoomId", "RoomName", "CountUsers", });
    internal_static_proto_files_UpdateRoomsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_files_UpdateRoomsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_files_UpdateRoomsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_files_UpdateRoomsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_files_UpdateRoomsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_files_UpdateRoomsResponse_descriptor,
        new java.lang.String[] { "LiteRoom", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
